chore: Update go installation scripts for go1.22

diff --git a/install/install/go_install_curl b/install/install/go_install_curl
--- a/install/install/go_install_curl
+++ b/install/install/go_install_curl
@@ -3,15 +3,20 @@
 
 go_install() {
 
-    # Download Go 
-    curl -fsSL -o /tmp/go1.21.1.linux-amd64.tar.gz \
-         https://go.dev/dl/go1.21.1.linux-amd64.tar.gz || 
-            printf "There was a problem downloading Go.\n" && return 1
+    # Download Go
+    if ! curl -fsSL -o /tmp/go1.22.1.linux-amd64.tar.gz \
+        https://go.dev/dl/go1.22.1.linux-amd64.tar.gz; then
+        printf "There was a problem downloading Go.\n" && return 1
+    fi
 
     # Extract Go
-    [[ -f /tmp/go1.21.1.linux-amd64.tar.gz ]] && 
-        sudo tar -C /usr/local -xzf /tmp/go1.21.1.linux-amd64.tar.gz ||
-            printf "There was a problem unzipping the Go tarball.\n" >&2 && return 1
+    if [[ -f /tmp/go1.21.1.linux-amd64.tar.gz ]]; then
+        if ! sudo tar -C /usr/local -xzf /tmp/go1.22.1.linux-amd64.tar.gz; then
+            printf >&2 "There was a problem unzipping the Go tarball.\n" && return 1
+        fi
+    else
+        printf >&2 "Go tarball not found in /tmp/ - Download failed?.\n"
+    fi
 
     # Add Go to PATH if it's not already
     go_path_exists=false
@@ -27,7 +32,7 @@ go_install() {
 
     if ! $go_path_exists; then
         printf "Adding Go to PATH...\n"
-        printf "export PATH=\$PATH:/usr/local/go/bin\n" >> ~/.bashrc
+        printf "export PATH=\$PATH:/usr/local/go/bin\n" >>~/.bashrc
         printf "Go added to PATH.\n"
     fi
 
@@ -47,4 +52,3 @@ if ! go_install; then
     printf "Could not install Go.\n"
     exit 1
 fi
-
