feat: Add error handling for install scripts

diff --git a/install/install/go_install_curl b/install/install/go_install_curl
--- a/install/install/go_install_curl
+++ b/install/install/go_install_curl
@@ -1,46 +1,50 @@
 #!/bin/bash
-# shellcheck disable=SC2059
+# shellcheck disable=SC2059,SC1091
 
 go_install() {
 
-    # Make installation directory
-    mkdir -p ~/install/go
-    cd ~/install/go || exit
+    # Download Go 
+    curl -fsSL -o /tmp/go1.21.1.linux-amd64.tar.gz \
+         https://go.dev/dl/go1.21.1.linux-amd64.tar.gz || 
+            printf "There was a problem downloading Go.\n" && return 1
 
-    # Download Go ()
-    if [[ ! -f /tmp/go1.21.1.linux-amd64.tar.gz ]]; then
-        curl -fsSL -o /tmp/go1.21.1.linux-amd64.tar.gz https://go.dev/dl/go1.21.1.linux-amd64.tar.gz
-    fi
+    # Extract Go
+    [[ -f /tmp/go1.21.1.linux-amd64.tar.gz ]] && 
+        sudo tar -C /usr/local -xzf /tmp/go1.21.1.linux-amd64.tar.gz ||
+            printf "There was a problem unzipping the Go tarball.\n" >&2 && return 1
 
-    # Check that the download succeeded
-    if [[ -f /tmp/go1.21.1.linux-amd64.tar.gz ]]; then
-        # Extract Go
-        sudo tar -C /usr/local -xzf /tmp/go1.21.1.linux-amd64.tar.gz
-
-        # Add Go to PATH if it's not already
-        go_path_exists=false
-        for file in ~/.bash*; do
-            if [[ $file == "$HOME/.bash_history" ]] || [[ $file == "$HOME/.bash_logout" ]]; then
-                continue
-            fi
-            if grep -q "export PATH=\$PATH:/usr/local/go/bin" "$file"; then
-                go_path_exists=true
-            fi
-        done
-
-        if [[ ! $go_path_exists ]]; then
-            echo "export PATH=\$PATH:/usr/local/go/bin" >> ~/.bashrc
+    # Add Go to PATH if it's not already
+    go_path_exists=false
+    for file in ~/.bash*; do
+        if [[ $file == "$HOME/.bash_history" ]] || [[ $file == "$HOME/.bash_logout" ]]; then
+            continue
         fi
+        if grep -q "/usr/local/go/bin" "$file"; then
+            printf "Go already exists in PATH.\n"
+            go_path_exists=true
+        fi
+    done
 
-        # Reload bash
-        source "$HOME/.bashrc"
-
-        # Confirm Installation
-        go version
-    else
-        echo "There was a problem downloading Go."
+    if ! $go_path_exists; then
+        printf "Adding Go to PATH...\n"
+        printf "export PATH=\$PATH:/usr/local/go/bin\n" >> ~/.bashrc
+        printf "Go added to PATH.\n"
     fi
-    cd - || exit
+
+    # Reload bash
+    source "$HOME/.bashrc"
+
+    # Confirm Installation
+    if go version; then
+        printf "\e[32mGo was successfully installed.\e[0m\n"
+        return 0
+    fi
+    printf "There was a problem downloading Go.\n"
+    return 1
 }
 
-go_install
+if ! go_install; then
+    printf "Could not install Go.\n"
+    exit 1
+fi
+
diff --git a/install/install/install_libssl_1-1 b/install/install/install_libssl_1-1
--- a/install/install/install_libssl_1-1
+++ b/install/install/install_libssl_1-1
@@ -1,16 +1,31 @@
 #!/bin/bash
 
-
+GREEN=$'\e[32m'
+RED=$'\e[31m'
+RESET=$'\e[0m'
 install_libssl1.1() {
-    curl -fsSL -o /tmp/libssl1.1_1.1.0g-2ubuntu4_amd64.deb http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb
+    if ! curl -fsSL -o /tmp/libssl1.1_1.1.0g-2ubuntu4_amd64.deb \
+        http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb; then
+        {
+            printf "%sDownload failed for libssl1.1%s" "${RED}" "${RESET}" >&2;
+            return 1;
+        }
+    fi
+
     if [[ -f /tmp/libssl1.1_1.1.0g-2ubuntu4_amd64.deb ]]; then
         printf "Download successful, attempting to install libssl1.1\n"
-        if sudo dpkg -i /tmp/libssl1.1_1.1.0g-2ubuntu4_amd64.deb; then
-            printf "Install was successful.\n"
-        fi
-    else
-        printf "There was a problem downloading libssl1.1"
+    fi
+
+    if ! sudo dpkg -i /tmp/libssl1.1_1.1.0g-2ubuntu4_amd64.deb && printf "Install was successful.\n"; then
+        {
+            printf "%sThere was a problem installing libssl1.1%s" "${RED}" "${RESET}" >&2;
+            return 1;
+        }
     fi
 }
 
-install_libssl1.1
+if ! install_libssl1.1; then
+    printf "%sCould not install libssl1.1\n%s" "${RED}" "${RESET}"
+    exit 1
+fi
+printf "%sSuccessfully installed libssl1.1\n%s" "${GREEN}" "${RESET}"
diff --git a/install/install/mods_install b/install/install/mods_install
--- a/install/install/mods_install
+++ b/install/install/mods_install
@@ -1,11 +1,41 @@
 #!/bin/bash
 
-mods_install(){
-    sudo mkdir -p /etc/apt/keyrings
-    curl -fsSL https://repo.charm.sh/apt/gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/charm.gpg
-    echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *" | sudo tee /etc/apt/sources.list.d/charm.list
-    sudo apt-get update && sudo apt-get install mods
+mods_install() {
+    if ! sudo mkdir -p /etc/apt/keyrings; then
+        printf "\e[32mFailed to create apt keyring.\e[0m\n" >&2;
+        return 1
+    fi
+
+    if ! {
+        curl -fsSL https://repo.charm.sh/apt/gpg.key |
+        sudo gpg --dearmor -o /etc/apt/keyrings/charm.gpg;
+    }; then 
+        printf "\e[31mFailed to download charm gpg key.\e[0m\n" >&2;
+        return 1
+    fi
+
+    if ! {
+        printf "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *\n" |
+        sudo tee /etc/apt/sources.list.d/charm.list; 
+    }; then
+        printf "\e[31mFailed to save charm gpg key.\e[0m\n" >&2;
+        return 1
+    fi
+
+    if ! { sudo apt-get update && sudo apt-get install mods -y -qq; }; then
+        printf "\e[31mFailed to download and install mods from apt.\e[0m\n" >&2;
+        return 1
+    fi
+
+    printf "Successfully installed mods.\n"
+    return 0
 }
-mods_install
+
+
+if ! mods_install; then
+    printf "\e[31mFailed to install mods.\e[0m\n"
+    exit 1
+fi
+
 
 
