refactor: Optimize with more robust error handling and safety with var quoting

diff --git a/scripts/.local/bin/discord-timestamp b/scripts/.local/bin/discord-timestamp
--- a/scripts/.local/bin/discord-timestamp
+++ b/scripts/.local/bin/discord-timestamp
@@ -1,31 +1,21 @@
 #!/bin/bash
-
-# TODO: Accept only date or only time
-#
-# TODO(feat): Add support for formatting:
-#   <t:unix_timestamp:t> - short time (e.g. 9:41 PM).
-#   <t:unix_timestamp:T> - long time (e.g. 9:41:30 PM).
-#   <t:unix_timestamp:d> - short date (e.g. 01/29/2026).
-#   <t:unix_timestamp:D> - long date (e.g. 29 January 2026).
-#   <t:unix_timestamp:f> - short date + time (e.g. `29 January 2026 9:41 PM`).
-#   <t:unix_timestamp:F> - full date + weekday + time.
-#   <t:unix_timestamp:R> - relative time (e.g. `in 2 hours`, `3 days ago`).
-
+# TODO: Accept only date or only time, default to current date/time
 
 declare DATE
 declare TIME
 declare INPUT
 declare FORMAT
 # CURRENT_DATE=$(date '+%F %R')
+declare CURRENT_DATE
 CURRENT_DATE=$(date '+%Y-%m-%d %H:%M')  # POSIX-friendly
-
-printf "Current date: %s\n" "$CURRENT_DATE"
 
 usage(){
     cat <<- EOF
 	Usage: 
 	    discord-timestamp [OPTIONS] DATE TIME
 
+        DATE must be formatted as YYYY-MM-DD  
+        TIME must be formatted as HH:MM  
 
 	Options: 
 	    -h, --help
@@ -44,8 +34,6 @@ usage(){
                 R	    Relative (in 2 days)
     Notes:
         Note that [OPTIONS] must come before the date and time.  
-        DATE must be formatted as YYYY-MM-DD  
-        TIME must be formatted as HH:MM  
 	EOF
 
 }
@@ -65,7 +53,7 @@ while [[ -n $1 && $1 =~ ^- && ! $1 == '--' ]]; do
                     printf "See --help for list of options and what they look like.\n"
                     exit 1;
                 fi
-                FORMAT=$1
+                FORMAT="$1"
             else
                 printf >&2 "Invalid or missing argument to -f|--format! Exiting.\n" 
                 exit 1;
@@ -83,24 +71,32 @@ done
 
 [[ $1 == '--' ]] && shift;
 
-[[ -n $1 && -n $2 ]] &&
-    DATE=$1 && TIME=$2 &&
-    INPUT=$(perl -pe 's/([-\d]+)\s+([:\d]+).*/\1 \2/' <<< "$DATE $TIME")
+if [[ -n $1 && -n $2 ]]; then
+    DATE="$1" && TIME="$2" &&
+    INPUT="$(perl -pe 's/([-\d]+)\s+([:\d]+).*/\1 \2/' <<< "$DATE $TIME")"
+else
+    printf >&2 '[ERROR]: Could not determine date and time. Did you put the options after the date?\n'
+    exit 1
+fi
 
-[[ -z $INPUT ]] &&
-    printf "No input provided. Using the current date/time (%s).\n" "${INPUT:=$CURRENT_DATE}"
+if [[ -z $INPUT ]]; then
+    printf "[ERROR]: No input provided. Using the current date/time (%s).\n" "${INPUT:=$CURRENT_DATE}"
+    usage
+    exit 1
+fi
 
-printf "Calculating Discord timestamp for: %s\n" "${INPUT}"
+# printf "Calculating Discord timestamp for: %s\n" "${INPUT}"
 
-EPOCH=$(date -d "${INPUT}" +%s 2>/dev/null)
+EPOCH="$(date -d "${INPUT}" +%s 2>/dev/null)"
 [[ -z $EPOCH ]] && {
-    printf "Failed to calculate the epoch time for the given date.\n"
+    printf "[ERROR]: Failed to calculate the epoch time for the given date.\n"
+    printf "[ERROR]: Does the given date (%s) exist?\n" "${DATE}/${TIME}"
+    usage
     exit 1
 }
 
-printf -v timestamp "<t:%s:%s>\n" "${EPOCH}" "${FORMAT:-f}"
-
-printf "\n\nTimestamp:\n%s\n" "$timestamp"
+# Output timestamp
+printf "<t:%s:%s>\n" "${EPOCH}" "${FORMAT:-f}"
 
 
 
