feat: Extend help docs, fix -f/--format option cmd

diff --git a/scripts/.local/bin/discord-timestamp b/scripts/.local/bin/discord-timestamp
--- a/scripts/.local/bin/discord-timestamp
+++ b/scripts/.local/bin/discord-timestamp
@@ -25,31 +25,43 @@ while [[ -n $1 && $1 =~ ^- && ! $1 == '--' ]]; do
     case $1 in
         -h|--help)
             cat <<- EOF
-			Code	Format
-			t	    Short time (9:00 AM)
-			T	    Long time (9:00:00 AM)
-			d	    Short date (08/09/2024)
-			D	    Long date (August 9, 2024)
-			f	    Short date/time (August 9, 2024 9:00 AM)
-			F	    Long date/time (Friday, August 9, 2024 9:00 AM)
-			R	    Relative (in 2 days)
+            Usage: 
+                discord-timestamp [OPTIONS] DATE TIME
+
+            Options: 
+                -f, --format <CODE>
+                    Displays the UNIX timestamp with the format code provided at the end.
+                    Available codes:
+
+                    Code	Format
+                    t	    Short time (9:00 AM)
+                    T	    Long time (9:00:00 AM)
+                    d	    Short date (08/09/2024)
+                    D	    Long date (August 9, 2024)
+                    f	    Short date/time (August 9, 2024 9:00 AM)
+                    F	    Long date/time (Friday, August 9, 2024 9:00 AM)
+                    R	    Relative (in 2 days)
 			EOF
             shift;
             exit 0;
             ;;
 
         -f|--format)
-            { [[ -n $2 && ! $2 =~ ^- ]] && shift; } || {
-                printf >&2 "Invalid or missing argument to -f|--format! Exiting.\n"; exit 1; }
-            if ! [[ $1 =~ ^[ftdFTDR]$ ]]; then
-                printf "Use --format to specify the format the date should have in discord.\n"
-                printf "Usage: -f | --format [f|t|d|D|f|F|R]\n"
-                printf "See --help for list of options and what they look like.\n"
+            if [[ -n $2 && ! $2 =~ ^- ]]; then
+                shift
+                if ! [[ $1 =~ ^[ftdFTDR]$ ]]; then
+                    printf "Usage: -f | --format [f|t|d|D|f|F|R]\n"
+                    printf "See --help for list of options and what they look like.\n"
+                    exit 1;
+                fi
+                FORMAT=$1
+            else
+                printf >&2 "Invalid or missing argument to -f|--format! Exiting.\n" 
                 exit 1;
             fi
-            FORMAT=$1
             shift;
             ;;
+
         *)
             printf "Unknown argument: %s\nUse --help for usage.\n" "$1"
             exit 1
@@ -75,5 +87,5 @@ EPOCH=$(date -d "${INPUT}" +%s 2>/dev/null)
     exit 1
 }
 
-printf "<t:%s:%s>\n" "${EPOCH}" "${FORMAT:=f}"
+printf "<t:%s:%s>\n" "${EPOCH}" "${FORMAT:-f}"
 
