feat(todo): Add option for reading webhook url from file

diff --git a/scripts/.local/bin/webhook-send b/scripts/.local/bin/webhook-send
--- a/scripts/.local/bin/webhook-send
+++ b/scripts/.local/bin/webhook-send
@@ -2,11 +2,16 @@
 
 declare -r DISCORD_WEBHOOK_URL="${DISCORD_WEBHOOK_URL:?Discord webhook URL must be set as an environment variable}"
 declare MESSAGE
+declare WEBHOOK_URL_FILE
 
 while [[ -n $1 && $1 =~ ^- && ! $1 == '--' ]]; do
     case "$1" in
         -m|--message)
             [[ -n $2 && ! $2 =~ ^- ]] && shift && MESSAGE="$1"
+            shift
+            ;;
+        -f|--webhook-url-file)
+            [[ -n $2 && ! $2 =~ ^- ]] && shift && WEBHOOK_URL_FILE="$1"
             shift
             ;;
         *) 
@@ -27,5 +32,8 @@ report-webhook(){
 
 if [[ -n $MESSAGE && -n $DISCORD_WEBHOOK_URL ]]; then
     report-webhook
+else
+    printf >&2 '[ERROR]: Missing message or webhook URL!\n'
+    exit 1
 fi
 
