fix: Remove redundant file check, move url definition to arg parsing

diff --git a/scripts/.local/bin/webhook-send b/scripts/.local/bin/webhook-send
--- a/scripts/.local/bin/webhook-send
+++ b/scripts/.local/bin/webhook-send
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-declare DISCORD_WEBHOOK_URL="${DISCORD_WEBHOOK_URL:?Discord webhook URL must be set as an environment variable}"
 declare MESSAGE
+declare WEBHOOK_URL
 declare WEBHOOK_URL_FILE
 
 while [[ -n $1 && $1 =~ ^- && ! $1 == '--' ]]; do
@@ -12,6 +12,12 @@ while [[ -n $1 && $1 =~ ^- && ! $1 == '--' ]]; do
             ;;
         -f|--webhook-url-file)
             [[ -n $2 && ! $2 =~ ^- ]] && shift && WEBHOOK_URL_FILE="$1"
+            if [[ -f $WEBHOOK_URL_FILE ]]; then
+                WEBHOOK_URL="$(head -n 1 "$WEBHOOK_URL_FILE")"
+            else
+                printf >&2 '[ERROR]: No such file: %s\n' "$WEBHOOK_URL_FILE"
+                exit 1
+            fi
             shift
             ;;
         *) 
@@ -22,22 +28,18 @@ while [[ -n $1 && $1 =~ ^- && ! $1 == '--' ]]; do
     :
 done
 
-if [[ -f $WEBHOOK_URL_FILE ]]; then
-    DISCORD_WEBHOOK_URL="$(head -n 1 "$WEBHOOK_URL_FILE")"
-fi
-
 report-webhook(){
     local PAYLOAD='{"content":"'$MESSAGE'"}'
 
     curl -X POST \
         -H "Content-Type: application/json" \
-        -d "$PAYLOAD" "$DISCORD_WEBHOOK_URL" || {
+        -d "$PAYLOAD" "$WEBHOOK_URL" || {
             printf >&2 '[ERROR]: Failed to send message to webhook!\n'
             return 1
         }
 }
 
-if [[ -n $MESSAGE && -n $DISCORD_WEBHOOK_URL ]]; then
+if [[ -n $MESSAGE && -n $WEBHOOK_URL ]]; then
     report-webhook
 else
     printf >&2 '[ERROR]: Missing message or webhook URL!\n'
